SourceCode/WebrootUI2.Web.Mvc/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebrootUI2.Web.Mvc.Controllers
{
    public class AppController : BaseController
    {
        public ActionResult ChangeLang(string lang)
        {
            if (lang != null && lang != string.Empty)
            {
                HttpCookie cookie = Request.Cookies["_culture"];

                if (cookie != null)
                    cookie.Value = lang;
                else
                {
                    cookie = new HttpCookie("_culture");
                    cookie.HttpOnly = false;
                    cookie.Value = lang;
                    cookie.Expires = DateTime.Now.AddYears(1);
                }
                Response.Cookies.Add(cookie); 
            }

            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            else
                return Redirect("/");
        }

        public ActionResult Help(string path)
        {
            string filename = path.Replace("/", "_") + ".html";
            HttpCookie cultureCookie = Request.Cookies["_culture"];

            string culture;
            if (cultureCookie != null)
                culture = cultureCookie.Value;
            else
                culture = Request.UserLanguages[0];
            
            if (string.IsNullOrEmpty(culture))
                culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name;

            string fullPath = "~/Views/Help/" + culture + "/" + filename;
            return new FilePathResult(fullPath, "text/html");
        }

        public ActionResult HttpNotFoundError()
        {
            Response.StatusCode = 404;
            Response.TrySkipIisCustomErrors = true;
            return View();
        }

        public ActionResult PermissionDeniedError()
        {
            return View();
        }
    }
}

SourceCode/WebrootUI2.Web.Mvc/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebrootUI2.Domain.Contracts.Tasks;
using WebrootUI2.Domain.Models;
using WebrootUI2.Infrastructure.Common.Log;
using WebrootUI2.Web.Mvc.Controllers.Queries;
using WebrootUI2.Web.Mvc.Controllers.ViewModels;
using WebrootUI2.Web.Mvc.Filters;
using WebrootUI2.Domain;

namespace WebrootUI2.Web.Mvc.Controllers
{
    [Authorize]
    [Permissions(AllowedPermissions = new Common.AdminPermission[]{
    Common.AdminPermission.EditSystemSettings})]
    public class SystemController : BaseController
    {
        private readonly ILogEventTask logEventTask;
        private readonly IUserTask userTask;
        private readonly IRoleTask roleTask;
        private readonly RoleQuery roleQuery;
        private readonly UserQuery userQuery;

        public SystemController(ILogEventTask logEventTask, IUserTask userTask, RoleQuery companyRoleQuery,
        UserQuery userQuery,IRoleTask roleTask)
        {
            this.userTask = userTask;
            this.logEventTask = logEventTask;
            this.roleQuery = companyRoleQuery;
            this.userQuery = userQuery;
            this.roleTask = roleTask;
        }


        #region Users list

        /// <summary>
        /// Load the Users list in the Audit view.
        /// </summary>
        public ActionResult Index()
        {
            var auditModel = new AuditModel() { Username = string.Empty, RoleName = string.Empty };

            if (Request.QueryString["isCa"] != null && Request.QueryString["isCa"] == "true" && HttpContext.Cache["auditModel"] != null)
            {
                var cachedAuditModel = (AuditModel)HttpContext.Cache["auditModel"];

                auditModel.Username = cachedAuditModel.Username;
                auditModel.RoleName = cachedAuditModel.RoleName;
                auditModel.TotalRecordsCount = cachedAuditModel.Users.Count;
                auditModel.Users = cachedAuditModel.Users.Take(Setting.Page_Size).ToList<UserModel>();
            }
            else
            {
                var users = new List<UserModel>();

                foreach (var user in userTask.GetAdminUsers())
                {
                    users.Add(new UserModel()
                    {
                        Name = user.UserName,
                        RoleName = user.Role.Name,
                        Id = user.UserId
                    });
                }

                auditModel.TotalRecordsCount = users.Count();
                auditModel.Users = users.Take(Setting.Page_Size).ToList<UserModel>();
                HttpContext.Cache["auditModel"] = new AuditModel() { Users = users };
            }

            return View(auditModel);
        }

        /// <summary>
        /// Search Users in the Audit 
        /// </summary>
        [HttpGet]
        public JsonResult UsersSearch(string username, string role)
        {

            var users = new List<UserModel>();
            var count = 0;

            var usersQuery = userTask.Search(username == null ? string.Empty : username, role == null ? string.Empty : role);

            foreach (var user in usersQuery)
            {
                users.Add(new UserModel()
                {
                    Name = user.UserName,
                    RoleName = user.Role.Name,
                    Id = user.UserId
                });
            }

            HttpContext.Cache["auditModel"] = new AuditModel() { Username = username, RoleName = role, Users = users };
            count = users.Count;

            return Json(new { status = "success", userList = users.Take(Setting.Page_Size).ToList<UserModel>(), recordsCount = count }
                , JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Fetch data from the cached users list in the page index change
        /// </summary>
        [HttpGet]
        public JsonResult PagingIndexChanged(int index)
        {
            var count = 0;
            var users = new List<UserModel>();
            var cachedAuditModel = (AuditModel)HttpContext.Cache["auditModel"];

            if (cachedAuditModel == null)
                return Json(new { status = "failed" });

            users = cachedAuditModel.Users.Skip((index - 1) * Setting.Page_Size).Take(Setting.Page_Size).ToList<UserModel>();
            count = cachedAuditModel.Users.Count;

            return Json(new { status = "success", usersList = users, currentIndex = index, recordsCount = count }, JsonRequestBehavior.AllowGet);

        }

        #endregion

        #region Logs

        /// <summary>
        /// Load Audit logs of the selected user.
        /// </summary>
        public ActionResult Audit()
        {
            var userId = Guid.Empty;

            if (Request.QueryString["userId"] == null ||
               !Guid.TryParse(Request.QueryString["userId"].ToString(), out userId))
            {
                TempData["error"] = "Inavlid url";
                return View(new List<LogEvent>());
            }

            Session["userId"] = userId;
            var logs = new List<LogModel>();

            var eventsQuery = logEventTask.GetLogByUserId(userId);

            foreach (var eventLog in eventsQuery)
            {
                logs.Add(new LogModel() { DisplayDate = eventLog.Date.ToString(), Level = eventLog.Level, Message = eventLog.Message });
            }

            HttpContext.Cache["Logs"] = logs;
            ViewBag.recordsCount = logs.Count;

            return View(logs.Take(Setting.Page_Size).ToList<LogModel>());
        }

        /// <summary>
        /// Fetch data from the cached log list in the page index change
        /// </summary>
        [HttpGet]
        public JsonResult AuditPagingIndexChanged(int index)
        {
            var count = 0;
            var logs = new List<LogModel>();

            var cachedLogs = (List<LogModel>)HttpContext.Cache["Logs"];

            if (cachedLogs == null)
                return Json(new { status = "failed" });

            logs = cachedLogs.Skip((index - 1) * Setting.Page_Size).Take(Setting.Page_Size).ToList<LogModel>();
            count = cachedLogs.Count;


            return Json(new { status = "success", logEvents = logs, currentIndex = index, recordsCount = count }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Search audit log events.
        /// </summary>
        [HttpGet]
        public JsonResult AuditSearch(DateTime? from, DateTime? to, string level, string message)
        {
            var userId = Guid.Empty;
            var logs = new List<LogModel>();

            if (!Guid.TryParse(Session["userId"].ToString(), out userId))
                return Json(new { status = "failed" });

            var eventList = logEventTask.Search(from, to, level, message, userId);

            foreach (var _event in eventList)
            {
                logs.Add(new LogModel() { DisplayDate = _event.Date.ToString(), Level = _event.Level, Message = _event.Message });
            }

            HttpContext.Cache["Logs"] = logs;
            return Json(new { status = "success", logEvents = logs.Take(Setting.Page_Size), recordsCount = logs.Count },
                JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/HttpNotFoundError.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="error_page">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
    @Styles.Render("~/Content/bootstrap", "~/Content/stylecss")
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Jockey+One" />
</head>
<body>
    <div class="error_box">
        <h1>404 Page/File not found</h1>
		<p>The page/file you've requested has been moved or taken off the site.</p>
		<a href="javascript:history.back()" class="back_link btn btn-small">Go back</a>
    </div>
</body>
</html>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/PermissionDeniedError.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html class="error_page">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
    @Styles.Render("~/Content/bootstrap", "~/Content/stylecss")
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Jockey+One" />
</head>
<body>
    <div class="error_box">
        <h1>Permission Denied</h1>
		<p>You have not permissions to perform this operation.</p>
		<a href="javascript:history.back()" class="back_link btn btn-small">Go back</a>
    </div>
</body>
</html>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/_Header.cshtml
@{
    ViewBag.Title = "";
}

<header>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand" href="#"><i class="icon-home icon-white"></i>WebrootUI2 Logo</a>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.Partial("_Menu")
                    @Html.Partial("_UserMenu")
                }
            </div>
        </div>
    </div>
</header>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/bundles/bootstrapjs")
    @Styles.Render("~/Content/bootstrap", "~/Content/css")
    @Styles.Render("~/Content/Gebo-Template")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/jqueryui")
    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/bundles/paging")
</head>
<body>
    @Html.Partial("_Header")
    <div id="contentwrapper">
        <div class="main_content">
            <div class="row-fluid">
                @if (IsSectionDefined("Sidebar"))
                {
                    <div id="sidebar" class="sidebar">
                        <div class="sidebar_inner">
                            <div id="side_accordion" class="accordion">
                                @RenderSection("Sidebar")
                            </div>
                        </div>
                    </div>
                    @Helpers.SidebarSwitch()
                }
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/_Menu.cshtml
@using WebrootUI2.Web.Mvc.Providers
@using WebrootUI2.Domain
<ul id="menu" class="nav">
    @if (User.Identity.IsAuthenticated)
    {
        @MenuDropDown(Resource.TransactionMenuItem,
            Html.ActionLink(Resource.TransactionsViewMenuItem, "Transactions", "Admin"),
            Html.ActionLink(Resource.RefundMenuItem, "Transactions", "Admin"),
            Html.ActionLink(Resource.ChargebookMenuItem, "Transactions", "Admin"),
            Html.ActionLink(Resource.ErrorMenuItem, "Transactions", "Admin"))
            
        @MenuDropDown(Resource.ReportsMenuItem,
            Html.ActionLink(Resource.DailySummaryMenuItem, "Reports", "Admin"),
            Html.ActionLink(Resource.MonthSummaryMenuItem, "Reports", "Admin"),
            Html.ActionLink(Resource.DepositMenuItem, "Reports", "Admin"),
            Html.ActionLink(Resource.ExpiryMenuItem, "Reports", "Admin"))
        
        @MenuDropDown(Resource.InvoicesMenuItem,
            Html.ActionLink(Resource.CreateInvoiceMenuItem, "Invoices", "Admin"),
            Html.ActionLink(Resource.HistoryMenuItem, "Invoices", "Admin"),
            Html.ActionLink(Resource.PaymentMenuItem, "Invoices", "Admin"))
        
        if (SecurityProvider.HasPermission((User == null ? "" : User.Identity.Name),
            new Common.AdminPermission[] { Common.AdminPermission.SuperAdminPermission, Common.AdminPermission.EditSystemSettings }))
        {
        @MenuDropDown(Resource.SystemMenuItem,
            Html.ActionLink(Resource.AuditMenuItem, "Index", "System"),
            Html.ActionLink(Resource.ConfigMenuItem, "Bin", "System"))    
        }
    }
</ul>

@helper MenuDropDown(string name, params IHtmlString[] lis)
{
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">@name<b class="caret"></b></a>
        <ul class="dropdown-menu">
            @foreach (var li in lis)
            {
                if (li != null)
                {
                <li>@li</li>
                }
            }
        </ul>
    </li>
}

@*@{    
    var controller = ViewContext.RouteData.Values["Controller"];
    var action = ViewContext.RouteData.Values["Action"];
    var language = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
    string content = "Help/_Help" + controller + action + "-" + language;
    string title = "Help on " + controller + " > " + action;
}
@Dialog("helpOnPage", title, content)*@
<div id="helpOnPage"></div>
@helper MenuItem(string name, string title, string action, string controller)
{
    if (name == ViewBag.MenuItem)
    {
    <li class="active ">
        @Html.ActionLink(title, action, controller)
    </li>
    }
    else
    {
    <li>
        @Html.ActionLink(title, action, controller)
    </li>
    }
}
@*@helper Dialog(string name, string title, string content)
{
    <div id="@name" title="@title"> 
        @try
        {       
            @Html.Partial(content)
        }
        catch (Exception ex)
        {
            var language = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
            string defaultContent = "Help/_Help" + "-" + language;
            @Html.Partial(defaultContent)
        }
    </div>   
}*@
<script>
    $(function () {
        $("#helpOnPage").dialog({ autoOpen: false });
    });

    function openHelpDialog() {
        var pathname = window.location.pathname;
        if (pathname != null && pathname != "" && pathname[0] == '/') {
            pathname = pathname.substring(1);
            if (pathname == "") {
                pathname = "Admin/Accounts";
            }
            var title = pathname.replace(new RegExp("/", "gm"), ' > ');
            $('#helpOnPage').dialog({ title: title });
            $('#helpOnPage').load("@Url.Action("Help", "App")" + "?path=" + pathname).dialog('open');
        }
    }
</script>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/_Profile.cshtml
@{
    ViewBag.Title = "_Profile";
}
<div class="span12">
    <h3 class="heading">User Profile</h3>
    <div class="row-fluid">
        <div class="span8">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group formSep">
                        <label class="control-label">Username</label>
                        <div class="controls text_line">
                            <strong>@User.Identity.Name</strong>
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label for="fileinput" class="control-label">User avatar</label>
                        <div class="controls">
                            <div data-fileupload="image" class="fileupload fileupload-new">
                                <div style="width: 80px; height: 80px;" class="fileupload-new thumbnail">
                                    <img src="http://www.placehold.it/80x80/EFEFEF/AAAAAA" alt="">
                                </div>
                                <div style="width: 80px; height: 80px; line-height: 80px;" class="fileupload-preview fileupload-exists thumbnail">
                                </div>
                                <span class="btn btn-file">
                                    <span class="fileupload-new">Select image</span>
                                    <span class="fileupload-exists">Change</span>
                                    <input type="file" id="fileinput" name="fileinput">
                                </span>
                                <a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Remove</a>
                            </div>
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label for="u_fname" class="control-label">Full name</label>
                        <div class="controls">
                            <input type="text" id="u_fname" class="input-xlarge" value="John Smith">
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label for="u_email" class="control-label">Email</label>
                        <div class="controls">
                            <input type="text" id="u_email" class="input-xlarge" value="johnSmith@example.com">
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label for="u_password" class="control-label">Password</label>
                        <div class="controls">
                            <div class="sepH_b">
                                <input type="password" id="u_password" class="input-xlarge" value="my_password">
                                <span class="help-block">Enter your password</span>
                            </div>
                            <input type="password" id="s_password_re" class="input-xlarge">
                            <span class="help-block">Repeat password</span>
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label class="control-label">I want to receive:</label>
                        <div class="controls">
                            <label class="checkbox inline">
                                <input type="checkbox" value="newsletter" id="email_newsletter" name="email_receive">
                                Newsletters
                            </label>
                            <label class="checkbox inline">
                                <input type="checkbox" value="sys_messages" id="email_sysmessages" name="email_receive" checked="checked">
                                System messages
                            </label>
                            <label class="checkbox inline">
                                <input type="checkbox" value="other_messages" id="email_othermessages" name="email_receive">
                                Other messages
                            </label>
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label class="control-label">Gender</label>
                        <div class="controls">
                            <label class="radio inline">
                                <input type="radio" value="male" id="s_male" name="f_gender" checked="checked">
                                Male
                            </label>
                            <label class="radio inline">
                                <input type="radio" value="female" id="s_female" name="f_gender">
                                Female
                            </label>
                        </div>
                    </div>
                    <div class="control-group formSep">
                        <label for="u_signature" class="control-label">Signature</label>
                        <div class="controls">
                            <textarea rows="4" id="u_signature" class="input-xlarge" style="overflow: hidden; word-wrap: break-word; max-height: 80px; min-height: 80px; height: 80px;">Lorem ipsum…</textarea>
                            <span class="help-block">Automatic resize</span>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <button class="btn btn-gebo" type="submit">Save changes</button>
                            <button class="btn">Cancel</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

SourceCode/WebrootUI2.Web.Mvc/Views/Shared/_UserMenu.cshtml
@using System.Threading
<ul class="nav user_menu pull-right">

    @if (User.Identity.IsAuthenticated)
    {
        <li class="divider-vertical"></li>
        <li class="dropdown">
            <a class="dropdown-toggle nav_condensed" data-toggle="dropdown" href="#">
                @switch (Thread.CurrentThread.CurrentCulture.ToString().Split(new char[] { '-' },
                    StringSplitOptions.RemoveEmptyEntries)[1].ToLower())
                {
                    default:
                    <i class="flag-us"></i>
                        break;
                    case "cn":
                    <i class="flag-cn"></i>
                        break;
                }
                <b class="caret"></b>

            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("changelang", "app", new { lang = "en-US" })">
                        <i class="flag-us"></i>
                        English
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("changelang", "app", new { lang = "zh-CN" })">
                        <i class="flag-cn"></i>
                        中文
                    </a>
                </li>
            </ul>
        </li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src=@Url.Content("~/Content/images/user_avatar.png") alt="" class="user_avatar">@User.Identity.Name<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("My profile", "Details", "User", new { id = Membership.GetUser(User.Identity.Name).ProviderUserKey }, null)</li>
                <li class="divider"></li>
                <li>@Html.ActionLink(Resource.SignOutMenuItem, "SignOut", "Admin")</li>
            </ul>
        </li>
        <li class="divider-vertical"></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#" onclick="openHelpDialog()">Help on this page</a></li>
                <li class="divider"></li>
                <li><a href="#">Download Full Manual</a></li>
            </ul>
        </li>
    }
</ul>